### ISSUE TITLE
Some guidance  

### ISSUE THREAD

**Issue by cerdamejiaj** [Topiary15/DRIVE-01#1]
I would like to try your project, but I'm having a hard time setting things up. Can you please give me some instructions on how to set things up and running the server to in EV3 Robot. 
Thanks

**Comment by Ugenteraan** [comment]
Hello,

Sure I'll help you. Do you have a Facebook account? If you do, please add
me. My Facebook email is m.ugenteraan@yahoo.com. I'll guide you there.

Thanks
Ugenteraan
